// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrM2q1AEFuo3zSCOENRzXbnQzGMWaXL5w',
    appId: '1:228277979693:web:b5057b7f6b19f4718046a4',
    messagingSenderId: '228277979693',
    projectId: 'flutter-firebase-chat-76c32',
    authDomain: 'flutter-firebase-chat-76c32.firebaseapp.com',
    storageBucket: 'flutter-firebase-chat-76c32.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvmGMWNsvHKYNzuzHk4oraQ81jV7vdSjg',
    appId: '1:228277979693:android:35b762410495ceb08046a4',
    messagingSenderId: '228277979693',
    projectId: 'flutter-firebase-chat-76c32',
    storageBucket: 'flutter-firebase-chat-76c32.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXTaIhOw7auWIDbQXcB7h355TX7aA56Hg',
    appId: '1:228277979693:ios:4762bd89c594e5028046a4',
    messagingSenderId: '228277979693',
    projectId: 'flutter-firebase-chat-76c32',
    storageBucket: 'flutter-firebase-chat-76c32.appspot.com',
    iosBundleId: 'com.toh1n.chatapp.flutterFirebaseChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXTaIhOw7auWIDbQXcB7h355TX7aA56Hg',
    appId: '1:228277979693:ios:8cf78c93db1afdd08046a4',
    messagingSenderId: '228277979693',
    projectId: 'flutter-firebase-chat-76c32',
    storageBucket: 'flutter-firebase-chat-76c32.appspot.com',
    iosBundleId: 'com.toh1n.chatapp.flutterFirebaseChatApp.RunnerTests',
  );
}
